### ISSUE TITLE
Update directory name

### ISSUE THREAD

**Issue by rmseifried** [UMassCDS/ds4cg2021-georeferencing#1]
When installing the software the first time, the directory installed via the `git clone` command is called "ds4cg2021-georeferencing." The instructions in the **Setup > Windows** section call the command `cd DS4CG-Automatic-Georeferencing/` which returns an error "The system cannot find the path specified."

**Recommended solution**: change the command to `cd ds4cg2021-georeferencing`

**Comment by SowmyaVasuki** [comment]
> When installing the software the first time, the directory installed via the `git clone` command is called "ds4cg2021-georeferencing." The instructions in the **Setup > Windows** section call the command `cd DS4CG-Automatic-Georeferencing/` which returns an error "The system cannot find the path specified."
> 
> **Recommended solution**: change the command to `cd ds4cg2021-georeferencing`

Thank You. Updated the instructions accordingly
